### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [VidicL13/MinCost-MaxKnapsackPacking#1]
Svetujem, da ima repozitorij bolj pomenljivo ime, npr. `MinCost-MaxKnapsackPacking`. @VidicL13, ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

**Comment by jaanos** [comment]
Vidim, da je urejeno, tako da zapiram.

**Comment by VidicL13** [comment]
Se opravičujem,pozabil sem zapreti.

8. nov. 2017 09:29 je oseba "Janoš Vidali" <notifications@github.com>
napisala:
